# Use the official lightweight Python image based on Alpine
FROM python:3.12-alpine

# Set the working directory
WORKDIR /app

# Add a simple script that prints a message
RUN echo 'print("Hello from a alpine Docker!")' > hello.py

CMD ["python", "hello.py"]